name: cache-images
on:
  schedule:
    - cron: "0 5 * * *"   # se ejecuta cada día a las 05:00 UTC
  workflow_dispatch:       # te permite lanzarlo manualmente

jobs:
  cache:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requests
        run: python -m pip install --upgrade pip requests

      - name: Cache images locally
        run: python automation/cache_images.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/imgcache/* public/data/products.json || true
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore(imgcache): refresh $(date -u +%F)"
            git push
          fi
